// react-components/MobileHeader.tsx
import { Menu, ShoppingCart, ArrowLeft } from 'lucide-react';
import { Sheet, SheetContent, SheetTrigger } from './ui/sheet';
import { SideMenu } from './SideMenu';
import { Button } from './ui/button';

interface MobileHeaderProps {
  isMenuOpen: boolean;
  setIsMenuOpen: (open: boolean) => void;
  onNavigate: (screen: 'dashboard' | 'compendio' | 'productSheet' | 'receitas' | 'novaReceita') => void;
  currentScreen: string;
  onBack: () => void;
}

export function MobileHeader({ 
  isMenuOpen, 
  setIsMenuOpen, 
  onNavigate,
  currentScreen,
  onBack
}: MobileHeaderProps) {
  const showBackButton = currentScreen !== 'dashboard';

  return (
    <header className="fixed top-0 left-0 right-0 bg-white border-b border-gray-200 z-50">
      <div className="flex items-center justify-between px-4 h-16">
        <div className="flex items-center gap-3">
          {showBackButton ? (
            <button 
              onClick={onBack}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <ArrowLeft className="w-6 h-6 text-gray-700" />
            </button>
          ) : (
            <Sheet open={isMenuOpen} onOpenChange={setIsMenuOpen}>
              <SheetTrigger asChild>
                <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                  <Menu className="w-6 h-6 text-gray-700" />
                </button>
              </SheetTrigger>
              <SheetContent side="left" className="w-[280px] p-0">
                <SideMenu onClose={() => setIsMenuOpen(false)} onNavigate={onNavigate} />
              </SheetContent>
            </Sheet>
          )}

          <div>
            <h1 className="text-emerald-700">WINFIT</h1>
            <p className="text-xs text-gray-600">AgroRevenda</p>
          </div>
        </div>

        <Button 
          size="sm" 
          className="bg-emerald-600 hover:bg-emerald-700 text-white px-4"
        >
          <ShoppingCart className="w-4 h-4 mr-1" />
          PDV
        </Button>
      </div>
    </header>
  );
}

// src/components/MobileHeader.vue
<template>
  <header class="fixed top-0 left-0 right-0 bg-white border-b border-gray-200 z-50">
    <div class="flex items-center justify-between px-4 h-16">
      <div class="flex items-center gap-3">
        <button 
          v-if="showBackButton"
          @click="goBack"
          class="p-2 hover:bg-gray-100 rounded-lg transition-colors"
        >
          <ArrowLeft class="w-6 h-6 text-gray-700" />
        </button>
        
        <button 
          v-else
          @click="toggleMenu"
          class="p-2 hover:bg-gray-100 rounded-lg transition-colors"
        >
          <Menu class="w-6 h-6 text-gray-700" />
        </button>

        <div>
          <h1 class="text-emerald-700 font-semibold">WINFIT</h1>
          <p class="text-xs text-gray-600">AgroRevenda</p>
        </div>
      </div>

      <button class="bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-lg text-sm flex items-center gap-1">
        <ShoppingCart class="w-4 h-4" />
        PDV
      </button>
    </div>

    <!-- Side Menu -->
    <div 
      v-if="isMenuOpen" 
      class="fixed inset-0 z-40"
      @click="closeMenu"
    >
      <div class="absolute inset-0 bg-black bg-opacity-50" />
      <div 
        class="absolute left-0 top-0 bottom-0 w-80 bg-white shadow-lg"
        @click.stop
      >
        <SideMenu @close="closeMenu" />
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAppStore } from '@/stores/app'
import { Menu, ArrowLeft, ShoppingCart } from 'lucide-vue-next'
import SideMenu from './SideMenu.vue'

const router = useRouter()
const route = useRoute()
const store = useAppStore()

const isMenuOpen = computed(() => store.isMenuOpen)

const showBackButton = computed(() => {
  return route.name !== 'dashboard'
})

const toggleMenu = () => {
  store.setMenuOpen(!store.isMenuOpen)
}

const closeMenu = () => {
  store.setMenuOpen(false)
}

const goBack = () => {
  if (route.name === 'product') {
    router.push('/compendio')
  } else if (route.name === 'nova-receita') {
    router.push('/receitas')
  } else {
    router.push('/')
  }
}
</script>
